apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: config-test
spec:
  selector:
    app: nginx
    name: nginx-ingress-microk8s
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-port
      port: 80
    - name: https-port
      protocol: TCP
      port: 443